name: anthishabrakho
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations: # Add this line
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.7+3
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.7+1
  introduction_screen: ^1.0.9
  provider: ^4.1.3
  http: ^0.12.1
  intl:
  cached_network_image: ^2.0.0
  flutter_spinkit: ^4.1.2
  pull_to_refresh:
  connectivity: ^2.0.2
  moneytextformfield:
  image_cropper: ^1.3.1
  flutter_slidable: ^0.5.7
  flutter_image_stack: ^0.0.3
  flutter_svg: ^0.19.3
  flare_flutter: ^2.0.1
  google_nav_bar: ^4.0.2
  syncfusion_flutter_charts:
  flutter_cupertino_date_picker: ^1.0.26+2
  charts_flutter: ^0.10.0

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - languages/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
